// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzofnujppddevelalhpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6b2ZudWpwcGRkZXZlbGFsaHBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMjEwMzgsImV4cCI6MjA2NTg5NzAzOH0.cuBPpNtxUIgNrBh4m0SoUf5cvyWZsO3FeGorxuydVlk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);